openapi: 3.1.1

servers:
  - url: https://localhost:8001
    description: smarthomeIX Agent

info:
  title: smarthomeIX Agent
  version: 1.0.0

  description: |
    smarthomeIX is a modular smart home system consisting of a central core service (**smarthomeIX**) and distributed **agents** that interface directly with smart devices. Communication between smarthomeIX and agents combines HTTP for control actions (like registration and configuration) and MQTT for asynchronous event and status updates.
tags:
  - name: Service
  - name: Integrations
  - name: Devices

paths:
  /service:
    get:
      tags:
        - Service
      operationId: GetService
      summary: Return service summary and basic configuration
      responses:
        200:
          $ref: '#/components/responses/Service'
  /integrations:
    get:
      tags:
        - Integrations
      operationId: GetIntegrations
      summary: Returns a list of integration handlers
      responses:
        200:
          $ref: '#/components/responses/Integrations'
  /devices:
    post:
      tags:
        - Devices
      operationId: PostDevice
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  format: uuid
                integrationId:
                  type: string
                config:
                  type: object
                  additionalProperties: true
              required:
                - id
                - integrationId
      summary: Register a new instance of a device
      responses:
        200:
          $ref: '#/components/responses/Device'
        400:
          $ref: '#/components/responses/400'
        409:
          $ref: '#/components/responses/409'
  /devices/{deviceId}:
    get:
      tags:
        - Devices
      operationId: GetDevice
      summary: Get device state
      parameters:
        - $ref: "#/components/parameters/pathDeviceId"
      responses:
        200:
          $ref: '#/components/responses/Device'
        404:
          $ref: '#/components/responses/404'
    delete:
      tags:
        - Devices
      operationId: DeleteDevice
      summary: Delete an instance of a device
      parameters:
        - $ref: "#/components/parameters/pathDeviceId"
      responses:
        204:
          $ref: '#/components/responses/204'
        404:
          $ref: '#/components/responses/404'

components:
  parameters:
    pathDeviceId:
      name: deviceId
      in: path
      required: true
      schema:
        type: string
        format: uuid
  schemas:
    Integration:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
    Service:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        version:
          type: string
        description:
          type: string
        brand:
          type: string
        developer:
          type: string
    Device:
      type: object
      properties:
        id:
          type: string
          format: uuid
        integrationId:
          type: string
        config:
          type: object
          additionalProperties: true
        telemetry:
          $ref: '#/components/schemas/Telemetry'
        registeredAt:
          type: string
          format: date-time
    Telemetry:
      type: object
      properties:
        data:
          type: object
        updatedAt:
          type: string
          format: date-time
  responses:
    Service:
      description: OK
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Service"
    Integrations:
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              integrations:
                type: array
                items:
                  $ref: "#/components/schemas/Integration"
    Device:
      description: OK
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Device"
    204:
      description: No Content
    400:
      description: Bad Request
    404:
      description: Not Found
    409:
      description: Conflict
